name: pytest
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
    - run: |
        pip install pytest
        pip install pytest-cov
        pytest failedtest.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
