name: ssh-test
on: [push]
jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        #host: ${{ secrets.HOST }}
        host: rheer@ecegrid.ecn.purdue.edu
        username: rheer
        password: 8rnyPU16ce
        #port: ${{ secrets.PORT }}
        script: |
          cd
          ls -a